Fix failing test under windows: explicitly use utf-8
[ERROR] testExportSpecObjectWithOptionalElements(org.itsallcode.openfasttrace.exporter.specobject.TestSpecobjectExporter)
Time elapsed: 0 s  <<< ERROR!
org.itsallcode.openfasttrace.exporter.ExporterException: Error exporting
to specobject format
        at org.itsallcode.openfasttrace.exporter.specobject.TestSpecobjectExporter.exportToString(TestSpecobjectExporter.java:169)
        at org.itsallcode.openfasttrace.exporter.specobject.TestSpecobjectExporter.testExportSpecObjectWithOptionalElements(TestSpecobjectExporter.java:113)
Caused by: javax.xml.stream.XMLStreamException: Underlying stream
encoding 'Cp1252' and input paramter for writeStartDocument() method
'UTF-8' do not match.
        at org.itsallcode.openfasttrace.exporter.specobject.TestSpecobjectExporter.exportToString(TestSpecobjectExporter.java:169)
        at org.itsallcode.openfasttrace.exporter.specobject.TestSpecobjectExporter.testExportSpecObjectWithOptionalElements(TestSpecobjectExporter.java:113)