Fix test failing under windows
[ERROR] testReportUncoveredTransientCoverageWithTwoLayersWrongVersionInDependencyOfItems  Time elapsed: 0.008 s  <<< ERROR!
org.itsallcode.openfasttrace.api.exporter.ExporterException: Generating document
        at org.itsallcode.openfasttrace.report.aspec.TestASpecReport.renderToString(TestASpecReport.java:509)
        at org.itsallcode.openfasttrace.report.aspec.TestASpecReport.testReportUncoveredTransientCoverageWithTwoLayersWrongVersionInDependencyOfItems(TestASpecReport.java:301)
Caused by: javax.xml.stream.XMLStreamException: Underlying stream encoding 'Cp1252' and input paramter for writeStartDocument() method 'UTF-8' do not match.
        at org.itsallcode.openfasttrace.report.aspec.TestASpecReport.renderToString(TestASpecReport.java:509)
        at org.itsallcode.openfasttrace.report.aspec.TestASpecReport.testReportUncoveredTransientCoverageWithTwoLayersWrongVersionInDependencyOfItems(TestASpecReport.java:301)